// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6eandyJURkmR2t_2G5-onPFb3r5eiRNE',
    appId: '1:450096783004:web:59b8f38abdf5f8d49b9759',
    messagingSenderId: '450096783004',
    projectId: 'project-ff0d1',
    authDomain: 'project-ff0d1.firebaseapp.com',
    storageBucket: 'project-ff0d1.appspot.com',
    measurementId: 'G-LWPXZSBS64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT60cqVe1oveTrRpyO8FxviU1K7dIBavk',
    appId: '1:450096783004:android:a2fe1463f99038929b9759',
    messagingSenderId: '450096783004',
    projectId: 'project-ff0d1',
    storageBucket: 'project-ff0d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6aAAU-9GwYtfx9aFRqorv0OGVm3E1j_0',
    appId: '1:450096783004:ios:b35741de63b94d399b9759',
    messagingSenderId: '450096783004',
    projectId: 'project-ff0d1',
    storageBucket: 'project-ff0d1.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6aAAU-9GwYtfx9aFRqorv0OGVm3E1j_0',
    appId: '1:450096783004:ios:b35741de63b94d399b9759',
    messagingSenderId: '450096783004',
    projectId: 'project-ff0d1',
    storageBucket: 'project-ff0d1.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6eandyJURkmR2t_2G5-onPFb3r5eiRNE',
    appId: '1:450096783004:web:8bc35b8dc28e9ac19b9759',
    messagingSenderId: '450096783004',
    projectId: 'project-ff0d1',
    authDomain: 'project-ff0d1.firebaseapp.com',
    storageBucket: 'project-ff0d1.appspot.com',
    measurementId: 'G-0J72ZS77KC',
  );

}